[agent]
name = "Coral-RepoUnderstanding"
version = "0.0.1"





# Config Options

[options.MODEL_NAME]
type = "string"
description = "Model name (e.g., mistral-medium-latest)"
default = "mistral-medium-latest"

[options.MODEL_PROVIDER]
type = "string"
description = "Model provider (e.g., mistralai, openai, anthropic)"
default = "mistralai"

[options.GITHUB_PERSONAL_ACCESS_TOKEN]
type = "string"
description = "Github token for the service"

[options.MODEL_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

# Config executable
[runtimes.executable]
command = [
  "powershell", "-ExecutionPolicy", "Bypass", "-Command",
  "D:/RegiSphere/Coral-Agents/Coral-RepoUnderstanding-Agent/venv/Scripts/python.exe",
  "D:/RegiSphere/Coral-Agents/Coral-RepoUnderstanding-Agent/main.py"
]

# Alternative command for another system (Linux/MacOS)
# command = ["bash", "examples/camel-search-maths/venv.sh", "examples/camel-search-maths/mcp_example_camel_interface.py"]
