[agent]
name = "Coral-interface"
version = "0.0.1"
description = "An agent that takes user input and interacts with other agents to fulfill requests"

# Config Options
[options.MODEL_NAME]
type = "string"
description = "Model name (e.g., mistral-medium-latest)"
default = "mistral-medium-latest"

[options.MODEL_PROVIDER]
type = "string"
description = "Model provider (e.g., mistralai, openai, anthropic)"
default = "mistralai"

[options.MODEL_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MODEL_BASE_URL]
type = "string"
description = "Base URL for the model (if you need to override the default)"
default = ""

[options.MODEL_MAX_TOKENS]
type = "string" 
description = "Maximum number of tokens per request"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "Model temperature (0.0 = deterministic, 1.0 = creative)"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

# Config executable
[runtimes.executable]
command = [
  "powershell", "-ExecutionPolicy", "Bypass", "-Command",
  "D:/Coral/RegiSphere/Coral-Agents/Coral-Interface-Agent/.venv/Scripts/python.exe",
  "D:/Coral/RegiSphere/Coral-Agents/Coral-Interface-Agent/main.py"
]

# Alternative command for another system (Linux/MacOS)
# command = ["bash", "examples/camel-search-maths/venv.sh", "examples/camel-search-maths/mcp_example_camel_interface.py"]
