[[local-agent]]
path = "D:/RegiSphere/Coral-Agents/Coral-Interface-Agent"

[[local-agent]]
path = "D:/RegiSphere/Coral-Agents/Coral-RepoUnderstanding-Agent"

[[local-agent]]
path = "D:/RegiSphere/Coral-Agents/Coral-FirecrawlMCP-Agent"  


