[[local-agent]]
path = "examples/camel-search-maths/interface"

[[local-agent]]
path = "examples/camel-search-maths/math"

[[local-agent]]
path = "examples/camel-search-maths/search"



[[local-agent]]
path = "external/Coral-Interface-Agent"

