[agent]
name = "deepsearch"
version = "0.0.1"
description = "Conducts in-depth research to uncover compliance requirements and risks."

[options.OPENAI_API_KEY]
type = "string"
description = "OpenAI API key for the model provider"

[options.LINKUP_API_KEY]
type = "string"
description = "Linkup API key for orchestration"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4.1')"
default = "gpt-4.1-mini"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai', etc)"
default = "openai"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = [
  "D:/RegiSphere/Coral-Agents/Coral-OpenDeepResearch-Agent/venv/Scripts/python.exe",
  "D:/RegiSphere/Coral-Agents/Coral-OpenDeepResearch-Agent/main.py"
]
